services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "database-env"
            POSTGRES_DB: "laravel"
        ports:
            - "3254:5432"
        volumes:
        - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
